* 2pem-viewer

** Installation and Compilation Instructions

*** OS X

	1. Install [[http://brew.sh][Homebrew]] (follow the instructions on the Homebrew website).
	2. Using the terminal, install the following packages using
       Homebrew: ~armadillo~, ~boost~, ~cmake~, ~fftw~, and ~glfw3~:

	   - ~brew install armadillo boost cmake fftw glfw3~

	   Along the way, Homebrew will probably complain to you about
       needing to install the Xcode developer tools---do so.
		 
	3. In a reasonable location, clone this git repository:

	   - ~git clone https://github.com/sampotter/2pem-viewer.git~

	4. Change directories into the repository, create a build
       directory (for an out-of-source build), run CMake, and build:

	   - ~cd 2pem-viewer~
	   - ~mkdir build~
	   - ~cd build~
	   - ~cmake -DCMAKE_BUILD_TYPE=Release ..~
	   - ~make~

	5. The resulting binaries in the ~build~ directory are
       ~./src/client~ and ~./src/server~.

** Using the Software

   The two binaries that are built, ~./src/client~ and ~./src/server~
   form a client-server pair. The server takes two arguments, a port
   and a ~.raw~ file containing recorded microscope output. For
   example, running:
#+BEGIN_SRC
# ./src/server 8888 <path-to-raw-file>
#+END_SRC
   will start the server and ready it to receive a connection from the
   client. The client tries to connect to localhost:8888 by default,
   so simply running:
#+BEGIN_SRC
# ./src/client
#+END_SRC
   is all that's necessary.
